name: Label importer

on:
  push:
    branches: [main]

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: EddieHubCommunity/gh-action-open-source-labels@v0.6.4
        with:
          github-token: ${{ secrets.DCTOKEN }}
          owner-name: "IAmTamal"
          repository-name: "TheExpertWaffle"
